name: HMD FoV
title: HMD FoV
#tagline:          ''
description: 'Database for FOV measurements of different HMDs and description of measurement techniques.'
#url: 
#baseurl:          '/database'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
permalink:  /:title.html
pygments: false
markdown: kramdown
# logo: /figures/cam_procedure.png
# show_downloads: true
remote_theme: pmarsceill/just-the-docs
#theme: jekyll-theme-minimal

# Setup
permalink:  /:title.html
pygments: false
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-titles-from-headings

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: :as_char
  toc_levels: 1..5
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  # smart_quotes:  ["apos", "apos", "ldquo", "rdquo"]
  use_coderay: false
  # input: GFM



